server:
  port: 5170
  servlet:
    session:
      timeout: 60
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cckfs
    #服务器用
#    username: cckfs
    #生产用
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


    #  application:
#    name: spring-security
#  security:
#    user:
#      name: user
#      roles: admin
#      password: 123456
    #  security:
    #    user:
    #      name: admin  # 用户名
    #      password: 123456  # 密码
    #    ??JAP??????
    #  jpa:
    #    hibernate.ddl-auto: update
    #    show-sql: true
    #    ??hibernate??????,?????????????????
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl